#!/usr/bin/env python

import json
import os
import sys

url = 'https://hivemind-data.firebaseapp.com/latest.json'
load_avgs = 'load_avgs'

user = sys.argv[1]
server = 'hive'
dept = 'cs'
os.system('curl -s https://hivemind-data.firebaseapp.com/latest.json > hivemind.json')
hivemind_txt = open('hivemind.json', 'r').read()
hivemind_json = hivemind_txt.replace('\n', '')

parsed = json.loads(hivemind_json)
data = parsed['data']
loads = []
dic = {}
for i in range(1,31): # there are 30 hive machines
	s = server + str(i) + '.' + dept
	if load_avgs in data[s]:
		dic[s] = data[s][load_avgs][1]
		loads.append(data[s][load_avgs][1])
	else:
		dic[s] = 1
		loads.append(1)


best = (min(dic.keys(), key=(lambda k: dic[k])))


c = 'ssh ' + user + '@' + str(best) + '.berkeley.edu'
os.system(c)
os.remove('hivemind.json')
